# -*- coding: utf-8 -*-
"""Purple_Block_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFmHga3Fh5w-pCAN83uMzylEu1yP9Lw4
"""

print("Hello World")

def best_buy_sell(prices):
    min_price = float('inf')
    max_profit = 0
    buy_price = sell_price = 0

    for price in prices:
        if price < min_price:
            min_price = price
        if price - min_price > max_profit:
            max_profit = price - min_price
            buy_price = min_price
            sell_price = price

    return buy_price, sell_price


prices = [5, 2, 1, 6, 9, 7]
buy, sell = best_buy_sell(prices)
print("Best Buy Price:", buy)
print("Best Sell Price:", sell)